#!/usr/bin/env python3
"""Regenerate gsr/gsr_headers.c from gsr/hdr/*.h (freestanding headers for the on-device tcc).
Run from the repo root:  python3 tools/embed_headers.py"""
import os, sys
root = os.path.join("gsrandroid", "src", "main", "cpp", "gsr")
hdr = os.path.join(root, "hdr")
out = os.path.join(root, "gsr_headers.c")
names = sorted(f for f in os.listdir(hdr) if f.endswith(".h"))
with open(out, "w") as o:
    o.write("/* GENERATED by tools/embed_headers.py from the hdr folder - do not edit. */\n")
    o.write('#include "gsr_headers.h"\n\n')
    for i, n in enumerate(names):
        data = open(os.path.join(hdr, n), "rb").read()
        o.write("static const unsigned char h%d[] = {" % i)
        o.write(",".join(str(b) for b in data))
        o.write(",0};\n")
    o.write("const GsrHeader gsr_headers[] = {\n")
    for i, n in enumerate(names):
        o.write('  {"%s", h%d, sizeof(h%d) - 1},\n' % (n, i, i))
    o.write("  {0, 0, 0}\n};\n")
print("wrote", out, len(names), "headers")
